// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace XStoreApp.ServiceClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderForUpdatingPriceAndQuantity
    {
        /// <summary>
        /// Initializes a new instance of the OrderForUpdatingPriceAndQuantity
        /// class.
        /// </summary>
        public OrderForUpdatingPriceAndQuantity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderForUpdatingPriceAndQuantity
        /// class.
        /// </summary>
        public OrderForUpdatingPriceAndQuantity(int? price = default(int?), int? quantity = default(int?))
        {
            Price = price;
            Quantity = quantity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public int? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

    }
}
