// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace XStoreApp.ServiceClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderInfoCreation
    {
        /// <summary>
        /// Initializes a new instance of the OrderInfoCreation class.
        /// </summary>
        public OrderInfoCreation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderInfoCreation class.
        /// </summary>
        public OrderInfoCreation(int? orderNumber = default(int?), System.DateTime? orderDate = default(System.DateTime?), string orderStatus = default(string))
        {
            OrderNumber = orderNumber;
            OrderDate = orderDate;
            OrderStatus = orderStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderNumber")]
        public int? OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderDate")]
        public System.DateTime? OrderDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderStatus")]
        public string OrderStatus { get; set; }

    }
}
