// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace XStoreApp.ServiceClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductForUpdating
    {
        /// <summary>
        /// Initializes a new instance of the ProductForUpdating class.
        /// </summary>
        public ProductForUpdating()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductForUpdating class.
        /// </summary>
        public ProductForUpdating(string productName = default(string), double? price = default(double?))
        {
            ProductName = productName;
            Price = price;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

    }
}
