// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace XStoreApp.ServiceClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Products
    {
        /// <summary>
        /// Initializes a new instance of the Products class.
        /// </summary>
        public Products()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Products class.
        /// </summary>
        public Products(int? productID = default(int?), string productName = default(string), string category = default(string), string productDescription = default(string), double? price = default(double?), int? quantity = default(int?), string manufacturer = default(string), System.DateTime? releaseDate = default(System.DateTime?), bool? availability = default(bool?), double? rating = default(double?))
        {
            ProductID = productID;
            ProductName = productName;
            Category = category;
            ProductDescription = productDescription;
            Price = price;
            Quantity = quantity;
            Manufacturer = manufacturer;
            ReleaseDate = releaseDate;
            Availability = availability;
            Rating = rating;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productID")]
        public int? ProductID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productDescription")]
        public string ProductDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "manufacturer")]
        public string Manufacturer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "releaseDate")]
        public System.DateTime? ReleaseDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availability")]
        public bool? Availability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rating")]
        public double? Rating { get; set; }

    }
}
