// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace XStoreApp.ServiceClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductForCreation
    {
        /// <summary>
        /// Initializes a new instance of the ProductForCreation class.
        /// </summary>
        public ProductForCreation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductForCreation class.
        /// </summary>
        public ProductForCreation(int? productId = default(int?), string productName = default(string), string category = default(string), double? price = default(double?))
        {
            ProductId = productId;
            ProductName = productName;
            Category = category;
            Price = price;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

    }
}
