// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace store.Database.Models
{
    public partial class Table2
    {
        public int? ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal? ProductPrice { get; set; }
    }
}