// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace store.Database.Models
{
    public partial class Table1
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string ProductDescription { get; set; }
        public decimal? Price { get; set; }
        public int? Quantity { get; set; }
        public string Manufacturer { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public bool? Availability { get; set; }
        public decimal? Rating { get; set; }
    }
}